# Generated by Django 4.1 on 2023-01-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vereinsapp', '0003_category_post_titelbild_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titelbild',
            field=models.ImageField(default='/media/gemeinsam.png', upload_to='media/'),
        ),
    ]
