# Generated by Django 4.1 on 2023-01-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vereinsapp', '0004_alter_post_titelbild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='beschreibung',
            field=models.CharField(default='', max_length=100),
        ),
    ]
