# Generated by Django 4.1 on 2023-02-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vereinsapp', '0006_post_bezirk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titelbild',
            field=models.ImageField(default='/media/gemeinsam.png', upload_to='../media/'),
        ),
    ]
